# Generated by Django 5.2.16 on 2026-07-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('identifier', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=8)),
                ('country', models.CharField(max_length=8)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('ownership_type_code', models.CharField(blank=True, choices=[('PU', 'Public'), ('PR', 'Private'), ('MA', 'Air Force'), ('MN', 'Navy'), ('MR', 'Army'), ('CG', 'Coast Guard')], default='', max_length=4)),
                ('fuel_types', models.CharField(blank=True, default='', max_length=64)),
                ('ctaf', models.CharField(blank=True, default='', max_length=32)),
                ('unicom', models.CharField(blank=True, default='', max_length=32)),
                ('wx', models.CharField(blank=True, default='', max_length=64)),
                ('phone_no', models.CharField(blank=True, default='', max_length=32)),
                ('ground', models.CharField(blank=True, default='', max_length=128)),
                ('tower', models.CharField(blank=True, default='', max_length=128)),
                ('tower2', models.CharField(blank=True, default='', max_length=128)),
                ('clearance_delivery', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['identifier'],
                'indexes': [models.Index(fields=['state'], name='api_airport_state_575aad_idx'), models.Index(fields=['country'], name='api_airport_country_278298_idx'), models.Index(fields=['city'], name='api_airport_city_ac1e8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('rwy_id', models.CharField(max_length=16)),
                ('tpa', models.IntegerField(blank=True, null=True)),
                ('rgt_tfc', models.CharField(blank=True, default='', max_length=16)),
                ('length_ft', models.IntegerField(blank=True, null=True)),
                ('width_ft', models.IntegerField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='api.airport')),
            ],
            options={
                'ordering': ['airport_id', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('airport', 'slot'), name='unique_runway_slot_per_airport')],
            },
        ),
    ]
